apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clickhouse

resources:
  - service.yaml
  - statefulset.yaml
  - poddisruptionbudget.yaml

commonLabels:
  app.kubernetes.io/name: zookeeper
  app.kubernetes.io/component: coordination
  app.kubernetes.io/part-of: clickhouse-cluster
