---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: clickhouse
  labels:
    app: zookeeper
spec:
  type: ClusterIP
  ports:
    - port: 2181
      targetPort: 2181
      name: client
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  namespace: clickhouse
  labels:
    app: zookeeper
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 2181
      targetPort: 2181
      name: client
    - port: 2888
      targetPort: 2888
      name: follower
    - port: 3888
      targetPort: 3888
      name: election
    - port: 7000
      targetPort: 7000
      name: metrics
  selector:
    app: zookeeper
