apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - servicemonitor.yaml
  - prometheusrule.yaml
  - grafana-dashboard-configmap.yaml

commonLabels:
  app.kubernetes.io/name: clickhouse-monitoring
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/part-of: clickhouse-cluster
