---
apiVersion: v1
kind: Namespace
metadata:
  name: clickhouse
  labels:
    name: clickhouse
    app: clickhouse
    managed-by: kubectl
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app: monitoring
    managed-by: kubectl
