apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clickhouse

resources:
  - service-account.yaml
  - configmap.yaml
  - clickhouse-installation.yaml
  - service-lb.yaml

commonLabels:
  app.kubernetes.io/name: clickhouse
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: clickhouse-cluster

# You can override configuration here
# configMapGenerator:
#   - name: clickhouse-custom-config
#     behavior: merge
#     literals:
#       - custom.xml=<your custom config>
