---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse-sa
  namespace: clickhouse
  annotations:
    # Uncomment and set your GCP service account for Workload Identity
    # iam.gke.io/gcp-service-account: clickhouse-sa@PROJECT_ID.iam.gserviceaccount.com
  labels:
    app: clickhouse
