---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-lb
  namespace: clickhouse
  labels:
    app: clickhouse
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    clickhouse.altinity.com/app: chop
    clickhouse.altinity.com/chi: clickhouse-cluster
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      protocol: TCP
    - name: tcp
      port: 9000
      targetPort: 9000
      protocol: TCP
